apiVersion: apis.kcp.dev/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: md5-594253e117fd79d79e47c1bdda949590.enterprisecontractpolicies.appstudio.redhat.com
spec:
  group: appstudio.redhat.com
  names:
    kind: EnterpriseContractPolicy
    listKind: EnterpriseContractPolicyList
    plural: enterprisecontractpolicies
    shortNames:
    - ecp
    singular: enterprisecontractpolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      description: EnterpriseContractPolicy is the Schema for the enterprisecontractpolicies
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EnterpriseContractPolicySpec is used to configure the Enterprise
            Contract Policy
          properties:
            authorization:
              description: Authorization for per component release approvals
              properties:
                components:
                  description: Components based authorization
                  items:
                    description: Authorization defines a release approval on a component
                      basis
                    properties:
                      authorizer:
                        description: Authorizer is the email address of the person
                          authorizing the release
                        type: string
                      changeId:
                        description: ChangeID is the identifier of the change, e.g.
                          git commit id
                        type: string
                      repository:
                        description: Repository of the component sources
                        type: string
                    type: object
                  type: array
              type: object
            configuration:
              description: Configuration handles policy modification configuration
                (collections, exclusions, inclusions)
              properties:
                collections;omitempty:
                  description: Collections set of predefined rules.
                  items:
                    type: string
                  type: array
                  x-kubernetes-list-type: set
                excludeRules:
                  description: ExcludeRules set of policy exclusions that, in case
                    of failure, do not block the success of the outcome.
                  items:
                    type: string
                  type: array
                  x-kubernetes-list-type: set
                includeRules:
                  description: IncludeRules set of policy inclusions that are added
                    to the policy evaluation. These override excluded rules.
                  items:
                    type: string
                  type: array
                  x-kubernetes-list-type: set
              type: object
            description:
              description: Description of the policy or it's intended use
              type: string
            exceptions:
              description: Exceptions under which the policy is evaluated as successful
                even if the listed policy checks have reported failure
              properties:
                nonBlocking:
                  description: NonBlocking set of policy exceptions that in case of
                    failure do not block the success of the outcome
                  items:
                    type: string
                  type: array
                  x-kubernetes-list-type: set
              type: object
            publicKey:
              description: Public key used to validate the signature of images and
                attestations
              type: string
            rekorUrl:
              description: URL of the Rekor instance. Empty string disables Rekor
                integration
              type: string
            sources:
              description: Sources of the policy
              items:
                description: PolicySource represents the configuration of the source
                  for the policy
                properties:
                  git:
                    description: GitRepository configures fetching of the policies
                      from a Git repository
                    properties:
                      repository:
                        description: Repository URL
                        type: string
                      revision:
                        default: main
                        description: Revision matching the branch, commit id or similar
                          to fetch. Defaults to `main`
                        type: string
                    required:
                    - repository
                    type: object
                type: object
              minItems: 1
              type: array
          required:
          - sources
          type: object
        status:
          description: EnterpriseContractPolicyStatus defines the observed state of
            EnterpriseContractPolicy
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}

---
